// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBouRBuBxUHw_mco0P9ph4lpsnEhbxEJQY',
    appId: '1:890651030417:web:3d50c09fb8bb9765386030',
    messagingSenderId: '890651030417',
    projectId: 'fir-9fa22',
    authDomain: 'fir-9fa22.firebaseapp.com',
    storageBucket: 'fir-9fa22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_OmefkyyIladyrNYSY-GONKiTSxta4Gk',
    appId: '1:890651030417:android:bede170d378c8ef6386030',
    messagingSenderId: '890651030417',
    projectId: 'fir-9fa22',
    storageBucket: 'fir-9fa22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB8gD_z3tWmrYZM52US7JRzfXGw1gkbmg',
    appId: '1:890651030417:ios:489ecd9a25ab5485386030',
    messagingSenderId: '890651030417',
    projectId: 'fir-9fa22',
    storageBucket: 'fir-9fa22.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );
}
